import { writable } from "svelte/store";

const Store = writable([
  {
    id: 1,
    title: "Inception arks",
    text: "Raise funds with the Inception Arks sale and distribute the NFTs on Exosama Network - a leading NFT chain on Polkadot",
    top: 80,
    left: 5,
    isDone: true,
  },
  {
    id: 2,
    title: "Charity donation",
    text: "Donate $125,000 to start organizing the service trips in partnership with Lions Club and based on our DAO’s votes",
    top: 75,
    left: 15,
    isDone: true,
  },
  {
    id: 3,
    title: "Conexus beta",
    text: "Launch Conexus beta - AI-powered interactive storytelling platform",
    top: 74,
    left: 30,
    isDone: true,
  },
  {
    id: 4,
    title: "Battle for nexon",
    text: "Launch the first lore-based game, fitting into Discord Episode 2",
    top: 70,
    left: 44,
    isDone: true,
  },
  {
    id: 5,
    title: "Ark assassin",
    text: "Launch the second lore-based game, fitting into Discord Episode 3",
    top: 67,
    left: 62,
    isDone: true,
  },
  {
    id: 6,
    title: "Potentials",
    text: "As the DAO voted -once Arks surpassed Exosama Network’s market cap- go multi-chain and unlock the Potentials out of Arks, doing the reveal of the dynamic evolvable avatars on Ethereum & Arbitrum",
    top: 64,
    left: 75,
    isDone: false,
  },
  {
    id: 7,
    title: "Dischordian Saga",
    text: "Roll out weekly AI-powered Story Nodes shaping the narrative and generating Potentials’ traits based on their voting",
    top: 53,
    left: 82,
    isDone: false,
  },
  {
    id: 8,
    title: "Conexus v1",
    text: "Launch the first version of CoNexus available to the public",
    top: 48,
    left: 70,
    isDone: false,
  },
  {
    id: 9,
    title: "Omnihub",
    text: "Launch a singular platform allowing holders to manage their assets in one place. It can be used for connecting multiple addresses to one account, customizing & staking NFTs, token burning, managing incoming rewards, etc.",
    top: 46,
    left: 57,
    isDone: false,
  },
  {
    id: 10,
    title: "Vortex",
    text: "Establish our weekly gaming lore-based events",
    top: 44,
    left: 44,
    isDone: false,
  },
  {
    id: 11,
    title: "Token",
    text: "Launch an ERC20 utility token",
    top: 43,
    left: 28,
    isDone: false,
  },
  {
    id: 12,
    title: "Multiverse bifrost",
    text: "Set up a bridge to our partners’ metaverses and games",
    top: 35,
    left: 13,
    isDone: false,
  },
  {
    id: 13,
    title: "Decentralized charity",
    text: "Create a multi-sig charity wallet that anyone can donate to",
    top: 27,
    left: 24,
    isDone: false,
  },
  {
    id: 14,
    title: "Project warhawk",
    text: "Launch a multiplayer top-down shooter game",
    top: 23,
    left: 38,
    isDone: false,
  },
  {
    id: 15,
    title: "Conexus v2",
    text: "Integrate text-to-video and/or multiplayer functionality to CoNexus, besides better UI and more NFT innovations",
    top: 22,
    left: 50,
    isDone: false,
  },
  {
    id: 16,
    title: "Service trip",
    text: "Hold the first global service trip fully funded, organized, and attended by DeGenerous DAO - in Turkey and India in February 2024.",
    top: 20,
    left: 65,
    isDone: false,
  },
  {
    id: 17,
    title: "Philanthropic platform",
    text: "Form the first decentralized charity fundraising platform with the help of NFT (Potentials) governance and Lions volunteers to allow crypto holders to easily donate to a verifiable cause (that anybody can create) and be able to showcase it through NFTs",
    top: 18,
    left: 80,
    isDone: false,
  },
]);

export default Store;
