import { writable } from "svelte/store";

const Store = writable([
  {
    id: 1,
    title: "Inception Arks",
    text: "Distribute Inception Arks",
    top: 80,
    left: 10,
    isDone: true,
  },
  {
    id: 2,
    title: "Service trips",
    text: "Start planning the service trips and distribution of $125 000 to charity",
    top: 60,
    left: 10,
    isDone: true,
  },
  {
    id: 3,
    title: "Conexus beta",
    text: "Launch Conexus beta - AI-powered interactive storytelling",
    top: 40,
    left: 10,
    isDone: true,
  },
  {
    id: 4,
    title: "Ark Entertainment System ",
    text: "Launch the Ark Entertainment System",
    top: 20,
    left: 20,
    isDone: false,
  },
  {
    id: 5,
    title: "lore-based mini-games ",
    text: "lore-based mini-games ",
    top: 40,
    left: 30,
    isDone: true,
  },
  {
    id: 6,
    title: "Avatar art reveal",
    text: "Go multi-chain and unlock the Potentials out of Arks - avatar art reveal",
    top: 60,
    left: 30,
    isDone: false,
  },
  {
    id: 7,
    title: "Dischordian Saga",
    text: "Launch the Dischordian Saga - weekly story nodes generating traits and shaping the narrative based on community voting",
    top: 80,
    left: 40,
    isDone: false,
  },
  {
    id: 8,
    title: "Multiverse Bifrost",
    text: "Launch the Multiverse Bifrost - connector to different metaverses and games",
    top: 60,
    left: 50,
    isDone: false,
  },
  {
    id: 9,
    title: "NFT staking, IMGR burning",
    text: "Launch the Module - allowing NFT staking, IMGR burning",
    top: 40,
    left: 50,
    isDone: false,
  },
  {
    id: 10,
    title: "IMGR - ERC20",
    text: "Launch IMGR - ERC20 utility token",
    top: 20,
    left: 60,
    isDone: false,
  },
  {
    id: 11,
    title: "Gaming & metaverse",
    text: "Launch weekly gaming & metaverse lore-based events",
    top: 40,
    left: 70,
    isDone: false,
  },
  {
    id: 12,
    title: "Multi-sig charity wallet",
    text: "Set up a multi-sig charity wallet that anyone can donate to",
    top: 60,
    left: 70,
    isDone: false,
  },
  {
    id: 13,
    title: "Decentralized charity fundraising platform",
    text: "Form a decentralized charity fundraising platform",
    top: 80,
    left: 80,
    isDone: false,
  },
]);

export default Store;
