<script lang="ts">
    import { fly } from 'svelte/transition';

    import ImageButton from "./ImageButton.svelte";
    import { state } from "@stores/homepage.ts";
    import { HomeSection } from "@types/homepage.ts";
    import { onMount } from "svelte";


    onMount(() => {
        let interval = setInterval(() => {
            state.update((s: HomeSection) => (s + 1) % HomeSection._number);
        }, 10000);

        state.subscribe(() => {
            clearInterval(interval);

            interval = setInterval(() => {
                state.update((s: HomeSection) => (s + 1) % HomeSection._number);
            }, 10000);
        })
    })

    const transition = { y: -100, duration: 500 }
</script>

<section class="potentials columns">
    <div class="image-grid">
        <ImageButton my_state={HomeSection.Potentials} image="/images/potentials/potentials2.png">Potentials</ImageButton>
        <ImageButton my_state={HomeSection.CoNexus} image="/images/potentials/conexus.jpg">CoNexus</ImageButton>
        <ImageButton my_state={HomeSection.SagaChallenges} image="/images/potentials/saga_gaming.png">Sagaverse Gaming</ImageButton>
        <ImageButton my_state={HomeSection.DischordianSaga} image="/images/potentials/dischordian.png">The Dischordian Saga</ImageButton>
        <ImageButton my_state={HomeSection.Philanthropy} image="/images/potentials/philanthropy.png">Philanthropy</ImageButton>
        <ImageButton my_state={HomeSection.Vision} image="/images/potentials/vision.png">Vision</ImageButton>
    </div>
    <div>
        {#if $state === HomeSection.Potentials}
            <div in:fly={transition}>
                <h2>Potentials</h2>
                <h3>The evolutionary NFT collection</h3>
                <p>
                    Potentials are 1,000 dynamic avatars that evolve on-chain through community participation.
                    As a Potential owner, you are at the core of all of our products
                    and have a say in shaping your avatar’s traits, attributes, and features through your decisions.
                    The art develops with your digital persona - mirroring your unique personality,
                    embedding your experiences, telling your story, and opening up custom trait-gated stories.
                </p>
                <div class="buttons">
                    <a class="button" href="https://degenerousdao.gitbook.io/wiki">JOIN</a>
                </div>
            </div>
        {:else if $state === HomeSection.CoNexus}
            <div in:fly={transition}>
                <h2>CoNexus</h2>
                <h3>Where Stories Know No Bounds</h3>
                <p>
                    CoNexus is our cutting-edge AI platform, offering Choose-Your-Own-Adventure stories
                    with infinite unique possibilities. These fascinating experiences, accompanied by powerful visuals,
                    music, and narration, are generated by artificial intelligence - adapting the story to your decisions in real-time
                    and ensuring that no adventure is ever the same.
                    The stories are customizable and expandable to the needs of any project out there.
                </p>
                <div class="buttons">
                    <a class="button" href="https://conexus.degenerousdao.com">ENTER</a>
                </div>
            </div>
        {:else if $state === HomeSection.SagaChallenges}
            <div in:fly={transition}>
                <h2>Sagaverse Gaming</h2>
                <h3>Another Layer of Immersion</h3>
                <p>
                    Immerse yourself in Sagaverse Gaming by participating in custom games and events
                    that seamlessly integrate with the Dischordian Saga's lore and enhance the NFTs’ narrative.
                    These experiences, created by ourselves and our Web3 partners,
                    provide extra rewards, encourage community interaction
                    and expand engagement across diverse games, metaverses, and blockchain platforms.
                </p>
                <div class="buttons">
                    <a class="button" href="https://degenerousdao.gitbook.io/wiki/our-products/sagaverse-gaming">ENTER</a>
                </div>
            </div>
        {:else if $state === HomeSection.DischordianSaga}
            <div in:fly={transition}>
                <h2>The Dischordian Saga</h2>
                <h3>Shape the Future</h3>
                <p>
                    Step into the captivating realm of The Dischordian Saga,
                    a community-governed story based on sci-fi lore that breathes life and depth into Potentials.
                </p>
                <p>
                    Every week, your on-chain votes influence the overall narrative,
                    adding unique traits to your NFTs that reveal your true character
                    and unlock mission-based story games within the CoNexus platform.
                </p>
                <div class="buttons">
                    <a class="button" href="https://degenerousdao.gitbook.io/wiki/our-products/dischordian-saga">ENTER</a>
                </div>
            </div>
        {:else if $state === HomeSection.Philanthropy}
            <div in:fly={transition}>
                <h2>Philanthropy</h2>
                <h3>Supercharging Giving</h3>
                <p>
                    Having raised $125k for charity through our initial NFT sale,
                    our DAO is already making a positive impact on the world.
                    Due to our partnership with the Lions Club,
                    we can ensure that 100% of the funds we raise for charity go directly to the people in need,
                    under well-organized, co-branded global service trips.
                </p>
                <p>
                    Our goal is to build a platform to gamify giving,
                    celebrating your verifiable philanthropic contributions on-chain
                    through unique NFT’s, traits, and aesthetics.
                    Each NFT tells a story, and together, we're crafting a narrative of generosity and positive change.
                </p>
                <div class="buttons">
                    <a class="button" href="https://degenerousdao.gitbook.io/wiki/philanthropy/dgrs-x-lions">ENTER</a>
                </div>
            </div>
        {:else if $state === HomeSection.Vision}
            <div in:fly={transition}>
                <h2>Vision</h2>
                <h3>Unleash Limitless Imagination to Shape a Better World</h3>
                <p>
                    At DeGenerous DAO, our vision transcends realms.
                    We envision a world where groundbreaking technology and unconventional ideas merge to create exceptional products and experiences.
                    By leveraging generative AI, dynamic NFTs, and the power of our vibrant community,
                    we aim to revolutionize narrative worldbuilding and character development.
                    Our ultimate goal is to harness these innovations to create apps with mass effect
                    and support charitable causes globally,
                    fostering a future where tech innovation and philanthropy walk hand in hand.
                </p>
                <p>
                    We aim to always build in alignment with our community,
                    actively encouraging involvement and input on our product roadmap.
                </p>
                <div class="buttons">
                    <a class="button" href="https://degenerousdao.gitbook.io/wiki">JOIN</a>
                </div>
            </div>
        {/if}
    </div>
</section>

<style lang="scss">
  @use "@styles/imports/index";

  :global(.columns) {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 2rem;

    @media screen and (max-width: 70rem) {
      flex-direction: column-reverse;
    }
  }

  .image-grid {
    display: grid;
    grid-template-columns: repeat(4, calc(25% - 0.75rem));
    gap: 1rem;
    width: 100%;

    :global(:first-child), :global(:last-child) {
      grid-column: 1/5;
    }

    @media screen and (max-width: 52rem) {
      grid-template-columns: repeat(2, 1fr);

      :global(:first-child), :global(:last-child) {
        grid-column: 1/3;
      }
    }
  }

  .buttons {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  p {
    margin-bottom: 0.5rem;
  }
</style>